"""Generate the compute adapter from the same surface/fog uniforms as the water mesh.

Run after editing shared .gdshaderinc files or underwater parameter declarations.
No second implementation of Gerstner, shore waves or ship interiors is maintained.
"""
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[2]


def expand(path):
    source = path.read_text(encoding="utf-8")
    return re.sub(r'#include "res://([^"]+)"',
                  lambda m: expand(ROOT / m[1]), source)


def generate():
    source = expand(ROOT / "shaders/liquid/underwater.gdshader")
    source = source[:source.index("void vertex()")]
    source = re.sub(r"^shader_type.*$|^render_mode.*$|^varying.*$", "", source, flags=re.M)
    layout, definitions = [], []
    slot, binding = 16, 6  # first 16 vec4s are view matrices; bindings 0..5 are images/buffers

    def uniform(match):
        nonlocal slot, binding
        kind, name, count = match[1], match[2], match[3]
        if name in ("depth_texture", "screen_texture"):
            return ""
        count = 128 if count == "MAX_INTERIORS" else int(count or 1)
        if kind == "sampler2D":
            layout.append(dict(name=name, type=kind, binding=binding))
            definitions.append(f"layout(set=0, binding={binding}) uniform sampler2D {name};")
            binding += 1
        else:
            layout.append(dict(name=name, type=kind, slot=slot, count=count,
                               color="source_color" in match[0]))
            value = f"uw.data[{slot}]"
            if count == 1:
                value += {"float": ".x", "int": ".x", "bool": ".x",
                          "vec2": ".xy", "vec3": ".xyz", "vec4": ""}[kind]
                if kind == "int":
                    value = f"floatBitsToInt({value})"
                elif kind == "bool":
                    value = f"({value} > 0.5)"
                definitions.append(f"#define {name} ({value})")
            slot += count
        return ""

    source = re.sub(r"^uniform\s+(\w+)\s+(\w+)(?:\[([^]]+)\])?[^;]*;", uniform, source, flags=re.M)
    for entry in layout:
        if entry.get("count", 1) > 1:
            def array(m, entry=entry):
                value = f'uw.data[{entry["slot"]} + ({m[1]})]'
                return f"floatBitsToInt({value}.x)" if entry["type"] == "int" else value
            source = re.sub(r'\b' + entry["name"] + r'\[([^]]+)\]', array, source)
    # Godot's initializer syntax differs from GLSL's array constructors.
    source = re.sub(r"(const float \w+\[\d+\] = )\{([^}]+)\}", r"\1float[](\2)", source)
    header = "// Generated by tools/water/build_underwater_shared.py. Do not edit.\n"
    header += "layout(set=0, binding=5, std430) readonly buffer WaterParams { vec4 data[]; } uw;\n"
    output = header + "\n".join(definitions) + "\n" + source
    # Small, namespaced parameter header for the fused atmosphere/water pass.
    # It intentionally contains no Gerstner functions: those run only in the cache.
    params = "// Generated by tools/water/build_underwater_shared.py. Do not edit.\n"
    params += "layout(set=1, binding=0, std430) readonly buffer WaterOpticsParams { vec4 data[]; } water_params;\n"
    for definition in definitions:
        if definition.startswith("#define "):
            params += definition.replace("#define ", "#define UW_").replace("uw.data", "water_params.data") + "\n"
    return output, json.dumps(dict(slots=slot, uniforms=layout), indent=2) + "\n", params


if __name__ == "__main__":
    import sys
    outputs = zip(("shaders/liquid/underwater_shared.glslinc", "data/resources/underwater_layout.json",
                   "shaders/liquid/underwater_params.glslinc"), generate())
    for name, content in outputs:
        path = ROOT / name
        if "--check" in sys.argv:
            assert path.read_text(encoding="utf-8") == content, f"Regenerate {name}"
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
